"""empty message

Revision ID: cd7851d7f554
Revises: 98a4842af51e
Create Date: 2018-08-08 20:53:35.362523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7851d7f554'
down_revision = '98a4842af51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halls',
    sa.Column('hid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('screen_type', sa.Integer(), nullable=False),
    sa.Column('seat_num', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cinemas.cid'], ),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_table('platoon',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_price', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('discount_price', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('hid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cinemas.cid'], ),
    sa.ForeignKeyConstraint(['hid'], ['halls.hid'], ),
    sa.ForeignKeyConstraint(['mid'], ['movies.mid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('seats',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_choose', sa.Boolean(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('hid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cinemas.cid'], ),
    sa.ForeignKeyConstraint(['hid'], ['halls.hid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    op.drop_table('platoon')
    op.drop_table('halls')
    # ### end Alembic commands ###
